version: '3.4'

services:
  time:
    build: ./showtime
    container_name: time
    env_file:
      - .env
    networks:
      - archid
    ports:
      - "127.0.0.1:5001:80"
  booking:
    build: ./booking
    container_name: booking
    env_file:
      - .env
    networks:
      - archid
    depends_on:
      - time
    ports:
      - "127.0.0.1:5002:80"
  movie:
    build: ./movie
    container_name: movie
    env_file:
      - .env
    networks:
      - archid
    ports:
      - "127.0.0.1:5003:80"
  user:
    build: ./user
    container_name: user
    ports:
      - "127.0.0.1:8080:80"
    env_file:
      - .env
    networks:
      - archid
    depends_on:
      - movie
      - booking

networks:
  archid: