# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import showtime_pb2 as showtime__pb2


class ShowTimesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllTimes = channel.unary_stream(
                '/ShowTimes/GetAllTimes',
                request_serializer=showtime__pb2.Empty.SerializeToString,
                response_deserializer=showtime__pb2.Time.FromString,
                )
        self.GetScheduleByDate = channel.unary_unary(
                '/ShowTimes/GetScheduleByDate',
                request_serializer=showtime__pb2.Date.SerializeToString,
                response_deserializer=showtime__pb2.Time.FromString,
                )


class ShowTimesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllTimes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScheduleByDate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShowTimesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllTimes': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllTimes,
                    request_deserializer=showtime__pb2.Empty.FromString,
                    response_serializer=showtime__pb2.Time.SerializeToString,
            ),
            'GetScheduleByDate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScheduleByDate,
                    request_deserializer=showtime__pb2.Date.FromString,
                    response_serializer=showtime__pb2.Time.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ShowTimes', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ShowTimes(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllTimes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ShowTimes/GetAllTimes',
            showtime__pb2.Empty.SerializeToString,
            showtime__pb2.Time.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetScheduleByDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ShowTimes/GetScheduleByDate',
            showtime__pb2.Date.SerializeToString,
            showtime__pb2.Time.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
